to_do/to_do/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('to_do_app/', include('to_do_app.urls')),
]

to_do/to_do_app/urls.py
from django.urls import path
from to_do_app import views


app_name = 'to_do_app'


urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('delete/<int:task_id>/', views.delete, name='delete'),
    path('edit/<int:task_id>/', views.edit, name='edit'),
    path('done_tasks/', views.done_tasks, name='done_tasks'),
    path('done_true/<int:task_id>', views.done_true, name='done_true'),
    path('reopen/<int:task_id>', views.reopen, name='reopen'),
]

to_do/to_do_app/models.py
from django.db import models
import datetime


# Create your models here.
class Task(models.Model):

    def __str__(self):
        return self.name

    class Priority(models.TextChoices):
        Lowest = 'Lowest'
        Low = 'Low'
        Medium = 'Medium'
        High = 'High'
        Highest = 'Highest'

    name = models.CharField(max_length=100)
    description = models.TextField(max_length=450, blank=True)
    priority = models.CharField(max_length=7, choices=Priority.choices, default=Priority.Medium)
    date = models.DateField(default=datetime.date.today())
    done_field = models.BooleanField(default=False)

to_do/to_do_app/forms.py
from .models import Task
from django import forms


class TodoForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'description', 'priority', 'date']

to_do/to_do_app/views.py
from django.shortcuts import render, redirect
import datetime
from .models import Task
from .forms import TodoForm
from django.http import HttpResponse


# Create your views here.
def index(request):
    task_list = Task.objects.filter(done_field=False)
    return render(request, 'to_do_app/index.html', {'task_list': task_list})


def add(request):
    if request.method == "POST":
        name = request.POST.get('name', '')
        description = request.POST.get('description', '')
        priority = request.POST.get('priority', '')
        date = request.POST.get('date', '')
        done_field = request.POST.get('done_field', False)
        task = Task(name=name, description=description, priority=priority, date=date, done_field=done_field)
        task.save()
        return redirect('/to_do_app')
    return render(request, 'to_do_app/add.html')


# def delete(request, task_id):
#     task = Task.objects.get(id=task_id)
#     if request.method == "POST":
#         task.delete()
#         return redirect('/')
#     return render(request, 'to_do_app/delete.html', {'task': task})


def delete(request, task_id):
    task = Task.objects.get(id=task_id)
    if request.method == "POST":
        task.delete()
        return redirect('/to_do_app/')



def done_true(request, task_id):
    task = Task.objects.get(id=task_id)
    if request.method == "POST":
        task.done_field = True
        task.save()
        return redirect('/to_do_app/')
    # return render(request, 'to_do_app/done_true.html', {'task': task})


def edit(request, task_id):
    task = Task.objects.get(id=task_id)
    form = TodoForm(request.POST or None, instance=task)
    if form.is_valid():
        form.save()
        return redirect('/to_to_app/')
    return render(request, 'to_do_app/edit.html', {'form': form, 'task': task})


def done_tasks(request):
    task_list = Task.objects.filter(done_field=True)
    return render(request, 'to_do_app/done_tasks.html', {'task_list': task_list})


def reopen(request, task_id):
    task = Task.objects.get(id=task_id)
    if request.method == "POST":
        task.done_field = False
        task.save()
        return redirect('/to_do_app/')

to_do/to_do_app/templates/to_do_app/add.html
{% extends 'to_do_app/base.html' %}
{% block title %}
    ToDo - New task
{% endblock %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <h3>Add task</h3>
                <form class='p-3 shadow' method="POST">
                    {% csrf_token %}
                        <div class="form-group">
                            <label for="name">Task name</label>
                            <input type="text" class="form-control" name="name" id="name" placeholder="Enter task name">
                        </div>
                        <div class="form-group">
                            <label for="description">Details</label>
                            <textarea class="form-control" name="description" id="description" placeholder="Enter task details" maxlength="450" rows="3"></textarea>
                        </div>
                        <div class="form-group">
                            <label for="priority">Priority</label>
                            <select class="form-control" name="priority" id="priority">
                                <option>Lowest</option>
                                <option>Low</option>
                                <option selected>Medium</option>
                                <option>High</option>
                                <option>Highest</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="date">Due date</label>
                            <input type="date" class="form-control" name="date" id="date">
                        </div>
                        <input type="submit" class="btn btn-success" value="Submit">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

to_do/to_do_app/templates/to_do_app/base.html
{% load todo_extras %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'to_do_app/style.css' %}">
        <title>{% block title %}{% endblock %}</title>
    </head>

    <body>
        <nav class="navbar navbar-light" aria-label="breadcrumb" style="background-color: #e3f2fd;">
            <a class="navbar-brand" href="{% url 'to_do_app:index' %}">ToDo</a>
            <ol class="breadcrumb" style="background-color: #e3f2fd;">
                <li class="breadcrumb-item"><a href="{% url 'to_do_app:index' %}">Active</a></li>
                <li class="breadcrumb-item"><a href="{% url 'to_do_app:done_tasks' %}">Done</a></li>
                <li class="breadcrumb-item"><a href="{% url 'to_do_app:add' %}">Add</a></li>
            </ol>
        </nav>
        {% block body %}

        {% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    </body>
</html>

to_do/to_do_app/templates/to_do_app/delete.html
{% extends 'to_do_app/base.html' %}
{% block title %}
    ToDo - Delete task
{% endblock %}

{% block body %}
    <form method="POST">
        {% csrf_token %}
        <p>Are you sure to delete the task?</p>
        <button class="btn btn-primary" type="submit">Yes</button>
    </form>
{% endblock %}




<!--{% extends 'to_do_app/base.html' %}-->

<!--{% block title %}-->
<!--    ToDo - Active tasks-->
<!--{% endblock %}-->

<!--{% block body %}-->

<!--    <div class="container-fluid">-->
<!--        <div class="row">-->
<!--            <div class="col">-->
<!--                <h3>Tasks to do</h3>-->
<!--                <p>Total: {{task_list|length}}</p>-->
<!--                {% for task in task_list %}-->
<!--                    <div class="shadow card">-->
<!--                        <div class="card-body">-->
<!--                            <h4 class="card-title">{{task.name}}</h4>-->
<!--                            {% if task.description %}-->
<!--                                <p><b>Details:</b></p>-->
<!--                                <p>{{task.description}}</p>-->
<!--                            {% endif %}-->
<!--                            <p><b>Priority:</b> {{task.priority}}</p>-->
<!--                            <p><b>Due date</b>: {{task.date}}</p>-->
<!--                            <form action="{% url 'to_do_app:done_true' task.id %}" method="POST">-->
<!--                                {% csrf_token %}-->
<!--                                    <input type="submit" class="btn btn-primary" value="Done">-->
<!--                            </form>-->
<!--                            <a class="btn btn-outline-primary" href="{% url 'to_do_app:edit' task.id %}">Edit</a>-->
<!--                            <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#delete_modal">-->
<!--                                Delete-->
<!--                            </button>-->
<!--                            <div class="modal fade" id="delete_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">-->
<!--                                <div class="modal-dialog modal-dialog-centered" role="document">-->
<!--                                    <div class="modal-content">-->
<!--                                        <div class="modal-header">-->
<!--                                            <h5 class="modal-title" id="delete_modal">Action approval</h5>-->
<!--                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">-->
<!--                                                <span aria-hidden="true">&times;</span>-->
<!--                                            </button>-->
<!--                                        </div>-->
<!--                                        <div class="modal-body">-->
<!--                                            Delete the task?-->
<!--                                        </div>-->
<!--                                        <div class="modal-footer">-->
<!--                                            <button type="button" class="btn btn-outline-primary" data-dismiss="modal">No</button>-->
<!--                                            <form action="{% url 'to_do_app:delete' task.id %}" method="POST">-->
<!--                                                {% csrf_token %}-->
<!--                                                    <input type="submit" class="btn btn-danger" value="Yes">-->
<!--                                            </form>-->
<!--                                        </div>-->
<!--                                    </div>-->
<!--                                </div>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                {% endfor %}-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--{% endblock %}-->

to_do/to_do_app/templates/to_do_app/done_tasks.html
{% extends 'to_do_app/base.html' %}
{% block title %}
    ToDo - Done tasks
{% endblock %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <h3>Done tasks</h3>
                <p>Total: {{task_list|length}}</p>
                {% for task in task_list %}
                    <div class="shadow card">
                        <div class="card-body">
                            <h4 class="card-title">{{task.name}}</h4>
                            {% if task.description %}
                                <p><b>Details:</b></p>
                                <p>{{task.description}}</p>
                            {% endif %}
                            <p><b>Priority:</b> {{task.priority}}</p>
                            <p><b>Due date:</b> {{task.date}}</p>
                            <div class="input-group">
                                <form action="{% url 'to_do_app:reopen' task.id %}" method="POST">
                                    {% csrf_token %}
                                    <input type="submit" class="btn btn-primary" value="Reopen">
                                </form>
                                <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#delete_modal">
                                    Delete
                                </button>
                                <div class="modal fade" id="delete_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                    <div class="modal-dialog modal-dialog-centered" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="delete_modal">Action approval</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                Delete the task?
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-outline-primary" data-dismiss="modal">No</button>
                                                <form action="{% url 'to_do_app:delete' task.id %}" method="POST">
                                                    {% csrf_token %}
                                                        <input type="submit" class="btn btn-danger" value="Yes">
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

to_do/to_do_app/templates/to_do_app/done_true.html
{% extends 'to_do_app/base.html' %}
{% block title %}
    ToDo - Done mark
{% endblock %}
{% block body %}
    <form method="POST">
        {% csrf_token %}
        <p>Are you sure this task is done?</p>
        <button class="btn btn-primary" type="submit">Yes</button>
    </form>
{% endblock %}

to_do/to_do_app/templates/to_do_app/edit.html
{% extends 'to_do_app/base.html' %}
{% block title %}
    ToDo - Edit task
{% endblock %}
{% block body %}
    <h3>Edit the task</h3>
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-success" value="Submit">
    </form>
{% endblock %}

to_do/to_do_app/templates/to_do_app/index.html
{% extends 'to_do_app/base.html' %}

{% block title %}
    ToDo - Active tasks
{% endblock %}

{% block body %}

    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <h3>Tasks to do</h3>
                <p>Total: {{task_list|length}}</p>
                {% for task in task_list %}
                    <div class="shadow card">
                        <div class="card-body">
                            <h4 class="card-title">{{task.name}}</h4>
                            {% if task.description %}
                                <p><b>Details:</b></p>
                                <p>{{task.description}}</p>
                            {% endif %}
                            <p><b>Priority:</b> {{task.priority}}</p>
                            <p><b>Due date</b>: {{task.date}}</p>
                            <form action="{% url 'to_do_app:done_true' task.id %}" method="POST">
                                {% csrf_token %}
                                <input type="submit" class="btn btn-primary" value="Done">
                                <a class="btn btn-outline-primary" href="{% url 'to_do_app:edit' task.id %}">Edit</a>
                                <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#delete_modal">
                                    Delete
                                </button>
                                <div class="modal fade" id="delete_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                    <div class="modal-dialog modal-dialog-centered" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="delete_modal">Action approval</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                Delete the task?
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-outline-primary" data-dismiss="modal">No</button>
                                                <form action="{% url 'to_do_app:delete' task.id %}" method="POST">
                                                    {% csrf_token %}
                                                        <input type="submit" class="btn btn-danger" value="Yes">
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}